version: '3.9'

services:
    database:
        image: postgres:14
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata: {}
